CREATE TABLE GROUP_DETAIL (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  GROUP_ID VARCHAR(255) NOT NULL,
  GROUP_NAME VARCHAR(255) NOT NULL,
  CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CREATED_BY VARCHAR(255) NOT NULL,
  UPDATED_BY VARCHAR(255) NOT NULL,
  IS_FLAG BOOLEAN DEFAULT TRUE
);


ALTER TABLE GROUP_DETAIL MODIFY COLUMN UPDATED_BY varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE GROUP_DETAIL MODIFY COLUMN CREATED_BY varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE GROUP_DETAIL MODIFY COLUMN UPDATE_DATE timestamp DEFAULT current_timestamp() on update current_timestamp() NULL;
