CREATE TABLE DEVICES
(
    DEVICE_ID INT PRIMARY KEY,
    DEVICE_NAME VARCHAR(255),
    DEVICE_TYPE VARCHAR(255),
    LOCATION VARCHAR(255),
    ACTIVE_FLAG VARCHAR
    (1),
    CREATED_BY VARCHAR
    (20),
    UPDATED_BY VARCHAR
    (20),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
);

CREATE TABLE READINGS
(
    READING_ID INT PRIMARY KEY,
    DEVICE_ID INT,

    TEMPERATURE DECIMAL(5, 2),
    HUMIDITY DECIMAL(5, 2),
    AIR_QUALITY DECIMAL(5, 2),
    ACTIVE_FLAG VARCHAR(1),
    CREATED_BY VARCHAR(20),
    UPDATED_BY VARCHAR(20),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES(DEVICE_ID)
);
